# Generated by Django 5.2.2 on 2025-06-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('cleaner', 'Cleaner'), ('Driver', 'Driver'), ('Security', 'Security')], max_length=10)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff_avatars/')),
            ],
        ),
    ]
