# Generated by Django 5.2.2 on 2025-06-23 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_otherstaff'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='staff_avatars/')),
            ],
        ),
        migrations.DeleteModel(
            name='OtherStaff',
        ),
    ]
