# Generated by Django 5.2.2 on 2025-06-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
