# Generated by Django 5.2.2 on 2025-06-18 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_remove_teacher_profile_picture_teacher_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='certificate',
        ),
    ]
