# Generated by Django 5.2.2 on 2025-06-18 11:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_teacher_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
