# Generated by Django 5.2.2 on 2025-06-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
