# Generated by Django 5.2.2 on 2025-06-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0002_alter_guardian_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='student',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
