# Generated by Django 5.2.2 on 2025-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentApp', '0004_rename_student_image_student_avatar_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.AlterField(
            model_name='guardian',
            name='address',
            field=models.CharField(blank=True, null=True),
        ),
    ]
